# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Henrik Simonsen <cybermaze@gmail.com>, 2014
# Henrik Simonsen <cybermaze@gmail.com>, 2014-2015
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2015-01-13 21:11+0000\n"
"Last-Translator: Henrik Simonsen <cybermaze@gmail.com>\n"
"Language-Team: Danish (http://www.transifex.com/projects/p/ipfire/language/"
"da/)\n"
"Language: da\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Fejlsøgning aktiveret"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Indlæser konfigurationsfil %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Fandt ingen indgange i konfigurationsfilen. Afslutter."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Dynamisk DNS opdatering af %(hostname)s (%(provider)s) fejlede:"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Dynamisk DNS opdatering af %(hostname)s (%(provider)s) returnerede en "
"ubehandlet undtagelse:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Fejl"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Netværksfejl"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"Serveren nægtede at modtage forespørgslen på grund af mistanke om misbrug af "
"brugerkontoen"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Serveren godtog ikke autentifikationen"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Serveren nægter alle opdateringer fra denne klient"

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "Konfigurationsfilen indeholder fejl"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Forbindelse nægtet"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Forbindelsen udløb"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "Værten kunne ikke findes i konfigurationsfilen"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Intern server fejl"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Netværket kan ikke nås"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Ikke fundet"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr "Forespørgsel fejl"

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "Kunne ikke oversætte DNS forespørgsel"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Service ikke tilgængelig"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "Opdateringen kunne ikke udføres"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Udbyder er ikke opsat korrekt"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Opdaterer %s tvunget"

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dynamisk DNS opdatering af %(hostname)s (%(provider)s) succesfuld"

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr "Opdaterer %(hostname)s (%(provider)s) pga. en IP adresse ændring"

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr "Opdaterer %(hostname)s (%(provider)s) pga. holdoff tiden er udløbet"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "Opdatering ikke nødvendig af %(hostname)s (%(provider)s)"

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr "Opdaterede ikke fordi der tidligere var et problem med %s"

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr "Prøver ikke igen"

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Sidste fejlmeddelelse:"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Yderligere opdateringer vil blive tilbageholdt indtil %s"

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
#, fuzzy
msgid "No valid FQDN was given"
msgstr "Ingen gyldig FQDN angivet."

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
#, fuzzy
msgid "Specified host does not exist"
msgstr "Den angivne vært findes ikke."

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
#, fuzzy
msgid "DNS error encountered"
msgstr "DNS fejl opstod."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr "Server svar: %s"

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Domæne ikke fundet."

#: ../src/ddns/providers.py:676
#, fuzzy
msgid "Account disabled or locked"
msgstr "Brugerkonto er deaktiveret."

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "Ugyldigt værtsnavn angivet"

#: ../src/ddns/providers.py:756
#, fuzzy
msgid "Hostname not marked as a dynamic host"
msgstr "Værtsnavn er ikke angivet som dynamisk vært."

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
#, fuzzy
msgid "Invalid IP address has been sent"
msgstr "Ugyldig IP adresse er sendt."

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Intet værtsnavn angivet."

#: ../src/ddns/providers.py:807
#, fuzzy
msgid "Account has been disabled"
msgstr "Brugerkonto er deaktiveret."

#: ../src/ddns/providers.py:813
#, fuzzy
msgid "Too many failed requests"
msgstr "For mange fejlede forespørgsler."

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
#, fuzzy
msgid "Invalid data has been sent"
msgstr "Ugyldig IP adresse er sendt."

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
#, fuzzy
msgid "Too frequent update requests have been sent"
msgstr "Har sendt for mange opdateringer."

#: ../src/ddns/providers.py:964
#, fuzzy
msgid "Malformed request has been sent"
msgstr "Misdannet forespørgsel blev sendt."

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Domæne ikke fundet."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr "En ugyldig IP adresse blev indsendt"

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Domæne ikke aktivt."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Ingen autentifikationsdetaljer angivet."

#: ../src/ddns/providers.py:1415
#, fuzzy
msgid "Invalid IPv4 address has been sent"
msgstr "Ugyldig IPv4 adresse sendt."

#: ../src/ddns/providers.py:1417
#, fuzzy
msgid "Invalid IPv6 address has been sent"
msgstr "Ugyldig IPv6 adresse sendt."

#: ../src/ddns/providers.py:1630
#, fuzzy
msgid "Account has been suspended"
msgstr "Brugerkonto er deaktiveret."

#: ../src/ddns/providers.py:1633
#, fuzzy
msgid "Account has been revoked"
msgstr "Brugerkonto er deaktiveret."

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr "Kører distribution: %s"

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "Forespørgsel header:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Svar header (Status kode %s):"

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Ugyldig værtsnavn angivet."
