# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# BluGen, 2014
# Michael Tremer <michael.tremer@ipfire.org>, 2012,2014
# Peter Cloudstone <rmg-mainz@web.de>, 2014
# BlockMall, 2014
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-08-04 14:54+0000\n"
"PO-Revision-Date: 2014-08-29 05:28+0000\n"
"Last-Translator: BlockMall\n"
"Language-Team: German (http://www.transifex.com/projects/p/ipfire/language/de/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:62
msgid "Debugging mode enabled"
msgstr "Debugmodus eingeschaltet"

#: ../src/ddns/__init__.py:86
#, python-format
msgid "Loading configuration file %s"
msgstr "Lade Konfigurationsdatei %s"

#: ../src/ddns/__init__.py:146
msgid "Found no entries in the configuration file. Exiting."
msgstr "Keine Einträge in der Konfigurationsdatei gefunden. Ende."

#: ../src/ddns/__init__.py:157
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) fehlgeschlagen"

#: ../src/ddns/__init__.py:164
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) erzeugte einen unerwarteten Fehler:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Fehler"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Netzwerkfehler"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr "Der Server hat die Anfrage aufgrund eines Missbrauchsverdachts zurückgewiesen"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Die Authentifizierung am Server ist fehlgeschlagen"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Der Server weist alle Aktualisierungen dieses Clients zurück"

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "Die Konfigurationsdatei weist Fehler auf"

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "Verbindung zurückgewiesen"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:212
msgid "Connection timeout"
msgstr "Verbindungstimeout"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "Der Host konnte in der Konfigurationsdatei nicht gefunden werden"

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "Interner Serverfehler"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "Netzwerk nicht erreichbar"

#: ../src/ddns/errors.py:117
msgid "Request error"
msgstr "Request-Fehler"

#: ../src/ddns/errors.py:125
msgid "Could not resolve DNS entry"
msgstr "DNS Eintrag konnte nicht aufgelöst werden"

#: ../src/ddns/errors.py:132
msgid "Service unavailable"
msgstr "Service nicht verfügbar"

#: ../src/ddns/errors.py:140
msgid "The update could not be performed"
msgstr "Die Aktualisierung konnte nicht ausgeführt werden"

#: ../src/ddns/providers.py:71
msgid "Provider is not properly configured"
msgstr "Der Anbieter ist nicht richtig konfiguriert"

#: ../src/ddns/providers.py:128
#, python-format
msgid "Updating %s forced"
msgstr "Aktualisierung von %s erzwungen"

#: ../src/ddns/providers.py:132
#, python-format
msgid "The dynamic host %(hostname)s (%(provider)s) is already up to date"
msgstr "Der dynamische Host %(hostname)s (%(provider)s) ist auf dem aktuellsten Stand"

#: ../src/ddns/providers.py:139
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) erfolgreich"

#: ../src/ddns/providers.py:220 ../src/ddns/providers.py:424
#: ../src/ddns/providers.py:929 ../src/ddns/providers.py:1077
msgid "No valid FQDN was given."
msgstr "Kein gültiger FQDN angegeben."

#: ../src/ddns/providers.py:222
msgid "Specified host does not exist."
msgstr "Der angebene Host existiert nicht."

#: ../src/ddns/providers.py:226
msgid "DNS error encountered."
msgstr "DNS-Fehler aufgetreten."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:229
#, python-format
msgid "Server response: %s"
msgstr "Antwort des Servers: %s"

#: ../src/ddns/providers.py:345
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:426 ../src/ddns/providers.py:472
msgid "Invalid hostname specified."
msgstr "Ungültiger Computername angegeben."

#: ../src/ddns/providers.py:428
msgid "Hostname not marked as a dynamic host."
msgstr "Computername nicht als dynamischer Computer markiert."

#: ../src/ddns/providers.py:430 ../src/ddns/providers.py:481
#: ../src/ddns/providers.py:658
msgid "Invalid IP address has been sent."
msgstr "Ungültige IP-Adresse abgeschickt."

#: ../src/ddns/providers.py:469
msgid "No hostname specified."
msgstr "Kein Hostname angegeben."

#: ../src/ddns/providers.py:478
msgid "Account has been disabled."
msgstr "Der Account wurde deaktiviert."

#: ../src/ddns/providers.py:484
msgid "Too many failed requests."
msgstr "Zu viele fehlgeschlagene Anfragen."

#: ../src/ddns/providers.py:575 ../src/ddns/providers.py:746
msgid "Domain not found."
msgstr "Domain nicht gefunden."

#: ../src/ddns/providers.py:609
msgid "An invalid IP address was submitted"
msgstr "Eine ungültige IP Adresse wurde übermittelt"

#: ../src/ddns/providers.py:748
msgid "Domain not active."
msgstr "Domain nicht aktiv."

#: ../src/ddns/providers.py:809
msgid "Invalid protocol has been given"
msgstr "Ungültiges Protokoll angegeben"

#: ../src/ddns/providers.py:903
msgid "No Auth details specified."
msgstr "Keine Authentifizierungsdetails angegeben."

#: ../src/ddns/providers.py:925
msgid "Invalid IPv4 address has been sent."
msgstr "Eine ungültige IPv4-Adresse wurde gesendet."

#: ../src/ddns/providers.py:927
msgid "Invalid IPv6 address has been sent."
msgstr "Eine ungültige IPv6-Adresse wurde gesendet."

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "Laufe auf Distribution: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "Request-Header:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Header der Antwort (Status Code %s):"
