# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Andrés Reyes <andres.rt@gmail.com>, 2012
# Roberto Peña <roberto.pena@northsecure.es>, 2015
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-09-29 14:20+0000\n"
"PO-Revision-Date: 2015-01-23 18:52+0000\n"
"Last-Translator: Roberto Peña <roberto.pena@northsecure.es>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/ipfire/language/es/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Modo de depuración habilitada"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Leyendo el archivo de configuración %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "No se han encontrado entradas en el fichero de configuración. Saliendo."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "La actualizacón dinámica de DNS para %(hostname)s (%(provider)s) ha fallado."

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr "La actualizacón dinámica de DNS para %(hostname)s (%(provider)s) ha lanzado una excepción no manejada."

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Error"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Error de red"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr "El servidor le negó la tramitación de la solicitud porque se sospecha cuenta abuso"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Autenticación en el servidor ha fallado"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "El servidor deniega las actualizaciones de este cliente"

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "El archivo de configuración tiene errores"

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "Conexión rechazada"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:218
msgid "Connection timeout"
msgstr "Tiempo de espera agotado de la conexión"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "El host no puede encontrar el archivo de configuración"

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "Error Interno del Servidor"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "Red inalcanzable"

#: ../src/ddns/errors.py:116
msgid "Not found"
msgstr "No encontrado"

#: ../src/ddns/errors.py:124
msgid "Request error"
msgstr "Error de solicitud"

#: ../src/ddns/errors.py:132
msgid "Could not resolve DNS entry"
msgstr "No se pudo resolver la entrada DNS"

#: ../src/ddns/errors.py:139
msgid "Service unavailable"
msgstr "Servicio no disponible"

#: ../src/ddns/errors.py:147
msgid "The update could not be performed"
msgstr "La actualización no puede ser ejecutada"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "El proveedor no está correctamente configurado"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Actualización %s forzada"

#: ../src/ddns/providers.py:170
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "La actualizacón dinámica de DNS para %(hostname)s (%(provider)s) ha resultado satisfactoria."

#: ../src/ddns/providers.py:194
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr "Una actualización para %(hostname)s (%(provider)s) está en ejecución porque una dirección IP ha cambiado"

#: ../src/ddns/providers.py:202
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr "Una actualización para %(hostname)s (%(provider)s) está en ejecución debido a que el tiempo de retención ha expirado"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:209
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "No se requiere actualización para %(hostname)s (%(provider)s)"

#: ../src/ddns/providers.py:228 ../src/ddns/providers.py:242
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr "Una actualización no se ha realizado porque las actualizaciones anteriores fallaron por %s"

#: ../src/ddns/providers.py:230
msgid "There will be no retries"
msgstr "No habrá reintentos"

#: ../src/ddns/providers.py:246
msgid "Last failure message:"
msgstr "Último mensaje de fallo:"

#: ../src/ddns/providers.py:251
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Otros cambios serán retenidos hasta %s"

#: ../src/ddns/providers.py:385 ../src/ddns/providers.py:612
#: ../src/ddns/providers.py:1191 ../src/ddns/providers.py:1340
msgid "No valid FQDN was given."
msgstr "El FQDN que se dió no es válido."

#: ../src/ddns/providers.py:387
msgid "Specified host does not exist."
msgstr "El host especificado no existe."

#: ../src/ddns/providers.py:391
msgid "DNS error encountered."
msgstr "Encontrado error de DNS."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:785
#, python-format
msgid "Server response: %s"
msgstr "Respuesta del servidor: %s"

#: ../src/ddns/providers.py:531
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:614 ../src/ddns/providers.py:661
msgid "Invalid hostname specified."
msgstr "Nombre de host especificado no es válido."

#: ../src/ddns/providers.py:616
msgid "Hostname not marked as a dynamic host."
msgstr "Nombre de host no marcado como un host dinámico."

#: ../src/ddns/providers.py:618 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:905
msgid "Invalid IP address has been sent."
msgstr "La dirección IP inválida ha sido enviada."

#: ../src/ddns/providers.py:658
msgid "No hostname specified."
msgstr "Nombre de host no especificado."

#: ../src/ddns/providers.py:667
msgid "Account has been disabled."
msgstr "La cuenta ha sido deshabilitada."

#: ../src/ddns/providers.py:673
msgid "Too many failed requests."
msgstr "Demasiados errores en las peticiones."

#: ../src/ddns/providers.py:776
msgid "Malformed request has been sent."
msgstr "Han sido enviadas peticiones malformadas."

#: ../src/ddns/providers.py:780
msgid "Too frequent update requests have been sent."
msgstr "Solicitudes de actualización demasiado frecuentes han sido enviadas."

#: ../src/ddns/providers.py:826 ../src/ddns/providers.py:1013
msgid "Domain not found."
msgstr "Dominio no encontrado:"

#: ../src/ddns/providers.py:861
msgid "An invalid IP address was submitted"
msgstr "Se presentó una dirección IP no válida"

#: ../src/ddns/providers.py:1015
msgid "Domain not active."
msgstr "Dominio no activo."

#: ../src/ddns/providers.py:1165
msgid "No Auth details specified."
msgstr "No hay detalles de autenticación especificados."

#: ../src/ddns/providers.py:1187
msgid "Invalid IPv4 address has been sent."
msgstr "Ha sido enviada una dirección IPv4 inválida."

#: ../src/ddns/providers.py:1189
msgid "Invalid IPv6 address has been sent."
msgstr "Ha sido enviada una dirección IPv6 inválida."

#: ../src/ddns/providers.py:1385
msgid "Invalid hostname specified"
msgstr "Nombre de host especificado inválido"

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "Corriendo en la distribuición: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "Cabecera de la petición:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Cabecera de respuesta (código de estado %s):"
