# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Khalil Delavaran <khalil.delavaran@gmail.com>, 2013-2014
# Reza Moghadam <r.moghadam@hotmail.com>, 2013
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-08-04 14:54+0000\n"
"PO-Revision-Date: 2014-06-24 04:35+0000\n"
"Last-Translator: Khalil Delavaran <khalil.delavaran@gmail.com>\n"
"Language-Team: Persian (http://www.transifex.com/projects/p/ipfire/language/"
"fa/)\n"
"Language: fa\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../src/ddns/__init__.py:62
msgid "Debugging mode enabled"
msgstr "پویای کردن حالت اشکال زدایی"

#: ../src/ddns/__init__.py:86
#, python-format
msgid "Loading configuration file %s"
msgstr "بارگذاری فایل پیکربندی %s "

#: ../src/ddns/__init__.py:146
msgid "Found no entries in the configuration file. Exiting."
msgstr "هیچ نوشته ای در فایل پیکربندی یافت نشد. در حال خارج شدن میباشید."

#: ../src/ddns/__init__.py:157
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "بروزرسانی Dynamic DNS برای %(hostname)s (%(provider)s) شکست خورد:"

#: ../src/ddns/__init__.py:164
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"بروزرسانی Dynamic DNS برای %(hostname)s (%(provider)s) یک استثنا اداره نشده "
"باطل :"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "ایراد"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "ایراد شبکه"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr "سرور، به دلیل سوء استفاده از حساب مشکوک، پردازش درخواست را رد کرد"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "احراز هویت در برابر سرور شکست خورده است"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "سرور هر گونه بروز رسانی از این کلاینت را رد می کند "

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "فایل پیکربندی ایراد دارد"

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "اتصال رد شد"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:212
msgid "Connection timeout"
msgstr "مهلت زمانی اتصال پایان یافت"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "میزبان در فایل پیکربندی یافت نمی شود"

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "ایراد درونی سرور"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "شبکه دور از دسترس است"

#: ../src/ddns/errors.py:117
msgid "Request error"
msgstr "ایراد در درخواست"

#: ../src/ddns/errors.py:125
msgid "Could not resolve DNS entry"
msgstr ""

#: ../src/ddns/errors.py:132
msgid "Service unavailable"
msgstr "سرویس در دسترس نیست"

#: ../src/ddns/errors.py:140
msgid "The update could not be performed"
msgstr "بروز رسانی نمی تواند انجام شود"

#: ../src/ddns/providers.py:71
msgid "Provider is not properly configured"
msgstr ""

#: ../src/ddns/providers.py:128
#, python-format
msgid "Updating %s forced"
msgstr "بروزرسانی %s به زور شد"

#: ../src/ddns/providers.py:132
#, fuzzy, python-format
msgid "The dynamic host %(hostname)s (%(provider)s) is already up to date"
msgstr "بروزرسانی Dynamic DNS برای %(hostname)s (%(provider)s) شکست خورد:"

#: ../src/ddns/providers.py:139
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dynamic DNS برای %(hostname)s (%(provider)s) بروزرسانی شد"

#: ../src/ddns/providers.py:220 ../src/ddns/providers.py:424
#: ../src/ddns/providers.py:929 ../src/ddns/providers.py:1077
msgid "No valid FQDN was given."
msgstr "FQDN بدست آمده درست نیست."

#: ../src/ddns/providers.py:222
msgid "Specified host does not exist."
msgstr "میزبان گزینش شده وجود ندارد."

#: ../src/ddns/providers.py:226
msgid "DNS error encountered."
msgstr "ایراد در DNS مواجه شده است."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:229
#, python-format
msgid "Server response: %s"
msgstr "پاسخ سرور: %s"

#: ../src/ddns/providers.py:345
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:426 ../src/ddns/providers.py:472
msgid "Invalid hostname specified."
msgstr "نام هاست گزینش شده درست نیست."

#: ../src/ddns/providers.py:428
msgid "Hostname not marked as a dynamic host."
msgstr "نام هاست به عنوان یک هاست پویا مشخص نیست."

#: ../src/ddns/providers.py:430 ../src/ddns/providers.py:481
#: ../src/ddns/providers.py:658
msgid "Invalid IP address has been sent."
msgstr "آدرس IP نادرست فرستاده شده است."

#: ../src/ddns/providers.py:469
msgid "No hostname specified."
msgstr "هیچ نام میزبانی مشخص نشده است."

#: ../src/ddns/providers.py:478
msgid "Account has been disabled."
msgstr "حساب کاربری ناپویا شده است."

#: ../src/ddns/providers.py:484
msgid "Too many failed requests."
msgstr "درخواست های بسیاری شکست خورده است."

#: ../src/ddns/providers.py:575 ../src/ddns/providers.py:746
msgid "Domain not found."
msgstr "دامین یافت نشد."

#: ../src/ddns/providers.py:609
#, fuzzy
msgid "An invalid IP address was submitted"
msgstr "آدرس IP نادرست فرستاده شده است."

#: ../src/ddns/providers.py:748
msgid "Domain not active."
msgstr "دامین پویا نشده است."

#: ../src/ddns/providers.py:809
#, fuzzy
msgid "Invalid protocol has been given"
msgstr "آدرس IP نادرست فرستاده شده است."

#: ../src/ddns/providers.py:903
msgid "No Auth details specified."
msgstr "جزئیات تایید مشخص نشده است."

#: ../src/ddns/providers.py:925
msgid "Invalid IPv4 address has been sent."
msgstr "آدرس IPv4 نامعتبر فرستاده شده است."

#: ../src/ddns/providers.py:927
msgid "Invalid IPv6 address has been sent."
msgstr "آدرس IPv6 نامعتبر فرستاده شده است."

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "در حال اجرا در توزیع: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "درخواست هدر:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "هدر پاسخ (کد وضعیت %s):"

#~ msgid "%s is already up to date"
#~ msgstr "%s بروزراسنی شده است"
