# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# André Felipe Morro <andre@andremorro.com>, 2012
# André Felipe Morro <andre@andremorro.com>, 2014
# Flávio Veras <flaviove@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-08-04 14:54+0000\n"
"PO-Revision-Date: 2014-07-04 10:46+0000\n"
"Last-Translator: Flávio Veras <flaviove@gmail.com>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/projects/p/"
"ipfire/language/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../src/ddns/__init__.py:62
msgid "Debugging mode enabled"
msgstr "Modo de depuração habilitado"

#: ../src/ddns/__init__.py:86
#, python-format
msgid "Loading configuration file %s"
msgstr "Carregando arquivo de configuração %s"

#: ../src/ddns/__init__.py:146
msgid "Found no entries in the configuration file. Exiting."
msgstr "Não foram encontradas entradas no arquivo de configuração. Saindo."

#: ../src/ddns/__init__.py:157
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) falhou:"

#: ../src/ddns/__init__.py:164
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) teve uma "
"exceção não tratada:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Erro"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Erro na rede"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"O servidor negou o processamento do pedido, por suspeita de abuso na conta"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Autenticação contra o servidor falhou"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "O servidor nega todas as atualizações deste cliente"

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "O arquivo de configuração tem erros"

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "Conexão recusada"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:212
msgid "Connection timeout"
msgstr "Tempo limite de conexão"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "O host não pôde ser encontrado no arquivo de configuração"

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "Erro Interno do Servidor"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "Rede inacessível"

#: ../src/ddns/errors.py:117
msgid "Request error"
msgstr "Erro de requisição"

#: ../src/ddns/errors.py:125
msgid "Could not resolve DNS entry"
msgstr ""

#: ../src/ddns/errors.py:132
msgid "Service unavailable"
msgstr "Serviço indisponível"

#: ../src/ddns/errors.py:140
msgid "The update could not be performed"
msgstr "A atualizalçao não pode ser realizada"

#: ../src/ddns/providers.py:71
msgid "Provider is not properly configured"
msgstr ""

#: ../src/ddns/providers.py:128
#, python-format
msgid "Updating %s forced"
msgstr "Atualição de %s forçada"

#: ../src/ddns/providers.py:132
#, fuzzy, python-format
msgid "The dynamic host %(hostname)s (%(provider)s) is already up to date"
msgstr "Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) falhou:"

#: ../src/ddns/providers.py:139
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""
"Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) bem sucedida"

#: ../src/ddns/providers.py:220 ../src/ddns/providers.py:424
#: ../src/ddns/providers.py:929 ../src/ddns/providers.py:1077
msgid "No valid FQDN was given."
msgstr "Não foi dado um FQDN válido."

#: ../src/ddns/providers.py:222
msgid "Specified host does not exist."
msgstr "Host especificado não existe."

#: ../src/ddns/providers.py:226
msgid "DNS error encountered."
msgstr "Encontrado erro de DNS."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:229
#, python-format
msgid "Server response: %s"
msgstr "Resposta do servidor: %s"

#: ../src/ddns/providers.py:345
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:426 ../src/ddns/providers.py:472
msgid "Invalid hostname specified."
msgstr "Hostname especificado inválido."

#: ../src/ddns/providers.py:428
msgid "Hostname not marked as a dynamic host."
msgstr "Hostname não marcado como host dinâmico."

#: ../src/ddns/providers.py:430 ../src/ddns/providers.py:481
#: ../src/ddns/providers.py:658
msgid "Invalid IP address has been sent."
msgstr "Endereço IP inválido foi enviado."

#: ../src/ddns/providers.py:469
msgid "No hostname specified."
msgstr "Nenhum nome de host foi espacificado."

#: ../src/ddns/providers.py:478
msgid "Account has been disabled."
msgstr "A conta foi desabilitada."

#: ../src/ddns/providers.py:484
msgid "Too many failed requests."
msgstr "Falha em muitas rwequisições."

#: ../src/ddns/providers.py:575 ../src/ddns/providers.py:746
msgid "Domain not found."
msgstr "Domínio não encontrado."

#: ../src/ddns/providers.py:609
#, fuzzy
msgid "An invalid IP address was submitted"
msgstr "Endereço IP inválido foi enviado."

#: ../src/ddns/providers.py:748
msgid "Domain not active."
msgstr "Domínio não está ativo."

#: ../src/ddns/providers.py:809
#, fuzzy
msgid "Invalid protocol has been given"
msgstr "Endereço IP inválido foi enviado."

#: ../src/ddns/providers.py:903
msgid "No Auth details specified."
msgstr "Nenhum detalhe de Autor especificado."

#: ../src/ddns/providers.py:925
msgid "Invalid IPv4 address has been sent."
msgstr "Endereço IPv4 inválido foi enviado."

#: ../src/ddns/providers.py:927
msgid "Invalid IPv6 address has been sent."
msgstr "Endereço IPv6 inválido foi enviado."

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "Em execução na distribuição: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "Header solicitada:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Cabeçalho de resposta (código de status %s):"

#~ msgid "%s is already up to date"
#~ msgstr "%s já está atualizado"
